# Generated by Django 5.2.5 on 2025-09-23 14:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colegio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AreaSocial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('ubicacion', models.CharField(blank=True, max_length=255, null=True)),
                ('hora_inicio_permitido', models.TimeField(blank=True, null=True)),
                ('hora_fin_permitido', models.TimeField(blank=True, null=True)),
                ('capacidad_maxima', models.PositiveSmallIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Restriccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ci', models.CharField(blank=True, max_length=40, null=True)),
                ('nombre', models.CharField(max_length=80)),
                ('apellido_paterno', models.CharField(blank=True, max_length=80, null=True)),
                ('apellido_materno', models.CharField(blank=True, max_length=80, null=True)),
                ('fecha_creada', models.DateField(auto_now_add=True)),
                ('telefono', models.CharField(blank=True, max_length=40, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('pais', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='colegio.pais')),
            ],
        ),
        migrations.CreateModel(
            name='Condominio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('direccion', models.CharField(blank=True, max_length=255, null=True)),
                ('responsable', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='colegio.persona')),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horario_inicio', models.TimeField()),
                ('horario_fin', models.TimeField()),
                ('fecha', models.DateField()),
                ('cantidad_gente', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('confirmada', 'Confirmada'), ('cancelada', 'Cancelada'), ('pendiente', 'Pendiente')], default='pendiente', max_length=20)),
                ('area_social', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='colegio.areasocial')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='colegio.persona')),
            ],
        ),
        migrations.CreateModel(
            name='Incumplimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('cancelado', 'Cancelado'), ('pendiente', 'Pendiente')], default='pendiente', max_length=20)),
                ('observaciones', models.CharField(blank=True, max_length=500, null=True)),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='colegio.persona')),
                ('restriccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='colegio.restriccion')),
            ],
        ),
        migrations.CreateModel(
            name='Unidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nro_modulo', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('nro_piso', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('nro_habitacion', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('valor_mensual', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('capacidad', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('nro_contrato', models.CharField(blank=True, max_length=80, null=True)),
                ('condominio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='colegio.condominio')),
                ('propietario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='colegio.persona')),
            ],
        ),
        migrations.CreateModel(
            name='Pagos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fecha', models.DateField()),
                ('duracion_meses', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('url_foto', models.CharField(blank=True, max_length=255, null=True)),
                ('metodo_pago', models.CharField(blank=True, max_length=60, null=True)),
                ('persona', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='colegio.persona')),
                ('unidad', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='colegio.unidad')),
            ],
        ),
        migrations.CreateModel(
            name='Visita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_visitante', models.CharField(max_length=80)),
                ('apellido_paterno', models.CharField(max_length=80)),
                ('apellido_materno', models.CharField(blank=True, max_length=80, null=True)),
                ('telefono', models.CharField(max_length=40)),
                ('fecha_ingreso', models.DateField()),
                ('hora_ingreso', models.TimeField(blank=True, null=True)),
                ('fecha_salida', models.DateField(blank=True, null=True)),
                ('hora_salida', models.TimeField(blank=True, null=True)),
                ('motivo', models.CharField(blank=True, max_length=255, null=True)),
                ('area_social', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='colegio.areasocial')),
                ('autorizado', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visitas_autorizadas', to='colegio.persona')),
                ('unidad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='colegio.unidad')),
            ],
        ),
        migrations.CreateModel(
            name='RestriccionArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_social', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='colegio.areasocial')),
                ('restriccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='colegio.restriccion')),
            ],
            options={
                'unique_together': {('restriccion', 'area_social')},
            },
        ),
        migrations.CreateModel(
            name='RolPersona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_asignada', models.DateField(auto_now_add=True)),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='colegio.persona')),
                ('rol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='colegio.rol')),
            ],
            options={
                'unique_together': {('persona', 'rol')},
            },
        ),
    ]
