# Generated by Django 5.2.6 on 2025-09-11 17:44

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colegio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AreaSocial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('ubicacion', models.CharField(blank=True, max_length=255, null=True)),
                ('hora_inicio_permitido', models.TimeField()),
                ('hora_fin_permitido', models.TimeField()),
                ('capacidad_maxima', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('codigo', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Restriccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
            ],
        ),
        migrations.RemoveField(
            model_name='persona',
            name='apellido',
        ),
        migrations.AddField(
            model_name='persona',
            name='apellido_materno',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='persona',
            name='apellido_paterno',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='persona',
            name='ci',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='persona',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='persona',
            name='fecha_creada',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='persona',
            name='telefono',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='persona',
            name='nombre',
            field=models.CharField(max_length=80),
        ),
        migrations.CreateModel(
            name='Condominio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('direccion', models.CharField(blank=True, max_length=255, null=True)),
                ('administrador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='condominios_administrados', to='colegio.persona')),
            ],
        ),
        migrations.AddField(
            model_name='persona',
            name='pais',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='colegio.pais'),
        ),
        migrations.CreateModel(
            name='RestriccionArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_social', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='colegio.areasocial')),
                ('restriccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='colegio.restriccion')),
            ],
            options={
                'unique_together': {('restriccion', 'area_social')},
            },
        ),
        migrations.AddField(
            model_name='areasocial',
            name='restricciones',
            field=models.ManyToManyField(through='colegio.RestriccionArea', to='colegio.restriccion'),
        ),
        migrations.CreateModel(
            name='RolPersona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_asignada', models.DateField(default=django.utils.timezone.now)),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='colegio.persona')),
                ('rol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='colegio.rol')),
            ],
            options={
                'unique_together': {('persona', 'rol')},
            },
        ),
        migrations.AddField(
            model_name='persona',
            name='roles',
            field=models.ManyToManyField(through='colegio.RolPersona', to='colegio.rol'),
        ),
        migrations.CreateModel(
            name='Unidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nro_modulo', models.PositiveSmallIntegerField()),
                ('nro_piso', models.PositiveSmallIntegerField()),
                ('nro_habitacion', models.PositiveSmallIntegerField()),
                ('valor_mensual', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('capacidad', models.PositiveSmallIntegerField()),
                ('nro_contrato', models.CharField(blank=True, max_length=80, null=True)),
                ('condominio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='colegio.condominio')),
                ('propietario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unidades_propiedad', to='colegio.persona')),
            ],
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fecha', models.DateField()),
                ('duracion_meses', models.PositiveSmallIntegerField()),
                ('url_foto', models.URLField(blank=True, max_length=255, null=True)),
                ('metodo_pago', models.CharField(blank=True, max_length=60, null=True)),
                ('persona', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='colegio.persona')),
                ('unidad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='colegio.unidad')),
            ],
        ),
        migrations.CreateModel(
            name='Visita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_visitante', models.CharField(max_length=80)),
                ('apellido_paterno', models.CharField(max_length=80)),
                ('apellido_materno', models.CharField(blank=True, max_length=80, null=True)),
                ('telefono', models.CharField(max_length=40)),
                ('fecha_ingreso', models.DateField()),
                ('hora_ingreso', models.TimeField(blank=True, null=True)),
                ('fecha_salida', models.DateField(blank=True, null=True)),
                ('hora_salida', models.TimeField(blank=True, null=True)),
                ('motivo', models.CharField(blank=True, max_length=255, null=True)),
                ('area_social', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='colegio.areasocial')),
                ('autorizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visitas_autorizadas', to='colegio.persona')),
                ('unidad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='colegio.unidad')),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horario_inicio', models.TimeField()),
                ('horario_fin', models.TimeField()),
                ('fecha', models.DateField()),
                ('cantidad_gente', models.PositiveSmallIntegerField()),
                ('estado', models.CharField(choices=[('confirmada', 'Confirmada'), ('cancelada', 'Cancelada'), ('pendiente', 'Pendiente')], default='pendiente', max_length=10)),
                ('area_social', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='colegio.areasocial')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='colegio.persona')),
            ],
            options={
                'indexes': [models.Index(fields=['fecha'], name='colegio_res_fecha_01859b_idx')],
            },
        ),
        migrations.CreateModel(
            name='Incumplimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('estado', models.CharField(choices=[('cancelado', 'Cancelado'), ('pendiente', 'Pendiente')], default='pendiente', max_length=10)),
                ('observaciones', models.TextField(blank=True, max_length=500, null=True)),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='colegio.persona')),
                ('restriccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='colegio.restriccion')),
            ],
            options={
                'indexes': [models.Index(fields=['persona'], name='colegio_inc_persona_6e7e20_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='unidad',
            index=models.Index(fields=['nro_modulo', 'nro_piso', 'nro_habitacion'], name='colegio_uni_nro_mod_ea2b62_idx'),
        ),
        migrations.AddIndex(
            model_name='pago',
            index=models.Index(fields=['fecha'], name='colegio_pag_fecha_bc299a_idx'),
        ),
        migrations.AddIndex(
            model_name='visita',
            index=models.Index(fields=['fecha_ingreso'], name='colegio_vis_fecha_i_d17cdf_idx'),
        ),
    ]
