# Generated by Django 5.2.5 on 2025-09-26 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colegio', '0003_persona_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unidad',
            name='condominio',
        ),
        migrations.RemoveField(
            model_name='persona',
            name='user',
        ),
        migrations.AddField(
            model_name='persona',
            name='clave',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name='Condominio',
        ),
    ]
