# Generated by Django 5.2.6 on 2025-09-28 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colegio', '0004_remove_unidad_condominio_remove_persona_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='unidad',
            name='estado',
            field=models.CharField(choices=[('disponible', 'Disponible'), ('ocupado', 'Ocupado')], default='disponible', max_length=20),
        ),
    ]
