# Generated by Django 5.2.6 on 2025-10-01 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colegio', '0005_unidad_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagos',
            name='AreaSocial',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='colegio.areasocial'),
        ),
    ]
