# Generated by Django 5.2.6 on 2025-10-01 00:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colegio', '0006_pagos_areasocial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pagos',
            name='AreaSocial',
        ),
        migrations.AddField(
            model_name='pagos',
            name='reserva',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='colegio.reserva'),
        ),
    ]
