# Generated by Django 5.2.6 on 2025-10-01 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colegio', '0007_remove_pagos_areasocial_pagos_reserva'),
    ]

    operations = [
        migrations.CreateModel(
            name='Placa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=10)),
                ('confianza', models.FloatField()),
                ('imagen_original', models.ImageField(blank=True, help_text='Imagen original de la placa vehicular', null=True, upload_to='placas/')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('procesado', models.BooleanField(default=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Placa Vehicular',
                'verbose_name_plural': 'Placas Vehiculares',
                'db_table': 'placas',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
